/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fft_JniFft */

#ifndef _Included_fft_JniFft
#define _Included_fft_JniFft
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fft_JniFft
 * Method:    internalCalculate
 * Signature: ([D[D)V
 */
JNIEXPORT void JNICALL Java_fft_JniFft_internalCalculate
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
